config/routes.rb
Rails.application.routes.draw do
  resources :pieces do
    resources :bookings, only: [ :new, :create, :show, :update ]
  end
  devise_for :users
  root to: 'pages#home'
  resources :users, only: [ :show ]
  get "dashboard", to: "pages#dashboard"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :piece
  has_one :review
  validates :date_start, presence: true
  validates :date_end, presence: true
  after_initialize :default_status

  def default_status
    self.status = "Pending"
  end
end

app/models/piece.rb
class Piece < ApplicationRecord
  belongs_to :user
  has_many :reviews, through: :bookings
  has_one_attached :photo
  validates :address, presence: true
  validates :photo, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  OPTIONS = ['Sculpture', 'Photography', 'Oil Painting', 'Painting', 'Illustration']
  validates :category, inclusion: { in: OPTIONS }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :pieces
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @piece = Piece.find(params[:piece_id])
    @booking = Booking.new
    @booking.piece = @piece
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @piece = Piece.find(params[:piece_id])
    @booking.piece = @piece
    @booking.user = current_user
    authorize @piece
    authorize @booking

    if @booking.save
      redirect_to piece_booking_path(@booking.id, @piece.id), notice: 'your booking has been sent!'
    else
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
    start = @booking.date_start
    endd = @booking.date_end
    @total = (start-endd).to_i * -1
  end

  private

  def booking_params
    params.require(:booking).permit(:date_start, :date_end)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/pieces_controller.rb
class PiecesController < ApplicationController
  before_action :set_piece, only: [:show, :edit, :update, :destroy]

  # GET /pieces
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @pieces = policy_scope(Piece)

    @markers = @pieces.geocoded.map do |piece|
      {
        lat: piece.latitude,
        lng: piece.longitude
      }
    end

    if params[:category].present?
      @pieces = Piece.where("category ILIKE ?", "%#{params[:category]}%")
    else
      @pieces = Piece.all
    end
  end

  # GET /pieces/1
  def show
    # @booking = Booking.new
    authorize @piece
    # authorize @booking
  end

  # GET /pieces/new
  def new
    @piece = Piece.new
    authorize @piece
  end

  # GET /pieces/1/edit
  def edit
    @piece = Piece.find(params[:id])
    authorize @piece
  end

  # POST /pieces
  def create
    @piece = Piece.new(piece_params)
    @piece.user = current_user
    authorize @piece

    if @piece.save
      redirect_to @piece, notice: 'piece was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /pieces/1
  def update
    @piece = Piece.find(params[:id])
    authorize @piece
    if @piece.update(piece_params)
      redirect_to piece_path(@piece), notice: 'piece was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /pieces/1
  def destroy
    authorize @piece
    @piece = Piece.find(params[:id])
    @piece.destroy
    redirect_to pieces_path(@piece), notice: 'piece was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_piece
    @piece = Piece.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def piece_params
    params.require(:piece).permit(:name, :height, :address, :length, :price, :category, :artist, :description, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    authorize @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="row ">
  <div class="col-xs-6 d-flex justify-content-around align-items-center">
    <% if @piece.photo.present? %>
    <%= cl_image_tag(@piece.photo.key, class:"card__image__booking shadow p-3 mt-3 bg-white rounded") %>
    <% end %>
    <div class="d-flex flex-column">
      <h1 class=""><%= @piece.name %></h1>
      <p><%= @piece.description %></p>
      <div class="details">
        <h2 class="piece_price_show_booking"><%= @piece.price %>$ Per Day</h2>
        <p class="mb-1"><b>Height:</b> <%= @piece.height %>cm | <b>Length:</b> <%= @piece.length %>cm</p>
        <p class="m-0"><b>Category:</b> <%= @piece.category %></p>
        <p><b>By:</b> <%= @piece.artist %></p>
        <div class="col-xs-6">

        <%= simple_form_for [@piece, @booking] do |f| %>
          <%= f.input :date_start, as: :date %>
          <%= f.input :date_end, as: :date %>
          <%= f.button :submit, "Create booking", class: "btn btn-search"%>
        <% end %>


            <%# <input type="date">
          <input type="date">
          <p class="piece_price_show_booking mt-2">Total:</p>
          <%= link_to "Confirm the booking", piece_bookings_path(@piece), class: "btn btn-ghost-green d-flex justify-content-center"%>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="thumbnail d-flex">
      <% if @booking.piece.photo.present? %>
      <%= cl_image_tag(@booking.piece.photo.key, class:"card__image shadow p-3 mb-4 bg-white rounded w-50") %>
      <% end %>
      <div class="align-self-center ml-5">
        <h2>Your booking has been sent!</h2>
        <p>From: <%= @booking.date_start %> To: <%= @booking.date_end %></p>
        <p class="m-0"><b>Total days:</b> <%= @total %></p>
        <p class="m-0"><b>Total amount:</b> $<%= @booking.piece.price * @total %></p>
        <p class="m-0"><b>Status: </b><%= @booking.status %></p>
        <p class="m-0"><b>Booking reference: </b>#<%= @booking.id %></p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Artbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

<div class="main-container">

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>


</div>

</html>

app/views/pages/home.html.erb
  <div class="container">
    <div class="container-center">
      <img src="https://i.icanvas.com/list-square/modern-living.jpg" alt="art piece">
      <div class="text-center">
        <div class="text-home">
          <h1 class="home_title"> ARTBNB</h1>
          <h2 class="home_slogan">Bring <mark class="highlight">art</mark> wherever you want</h2>
        </div>
        <%= link_to "Start your search", pieces_path , class: "nav-link btn-search mx-auto" %>
      </div>
    </div>
  </div>

app/views/pieces/_form.html.erb
<%= simple_form_for(@piece) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :height, :label => "Height (cm)" %>
    <%= f.input :length, :label => "Length (cm)" %>
    <%= f.input :price, :label => "Price ($)" %>
    <%= f.input :address %>
    <%= f.input :category %>
    <%= f.input :artist %>
    <%= f.input :description %>
    <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pieces/edit.html.erb
<div class="new-page">

  <div class="row justify-content-center">

    <div class="new-form mt-3">
      <%= simple_form_for(@piece) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="form-inputs">
          <%= f.input :name, placeholder: "title of the piece" %>
          <div class="dimensions">
            <%= f.input :height, :label => "Height", placeholder: "in cm"  %>
            <%= f.input :length, :label => "Length", placeholder: "in cm" %>
          </div>
          <%= f.input :price, :label => "Price ($) per day" %>
          <%= f.input :address %>
          <%= f.input :artist, placeholder: "full name" %>
          <%= f.input :description, placeholder: "few words about the art piece" %>
          <%= f.input :photo, as: :file %>
          <div class="category d-flex justify-content-center">
            <%= f.select :category, options_for_select(%w[Painting Photography Sculpture Illustrations]), prompt: "Choose your category" %>
          </div>
        </div>
        <div class="d-flex justify-content-center mb-3 mt-3">
          <div class="form-actions btn btn-ghost">
            <%= f.button :submit %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <br>

  <div class="d-flex justify-content-center mt-3">
    <%= link_to "Back", piece_path, class: "btn btn-ghost" %>
  </div>

  <br><br>

</div>

app/views/pieces/index.html.erb
<div class="container-index">

  <%# Starting cards + map container  %>
  <div class="cards">


    <div class="container-categories">
      <%= form_tag pieces_path, method: :get do %>

      <div class="search_category_boxes">
        <div class="search_category">
          <%= label_tag "Sculpture"%>
          <%= radio_button_tag 'category', "Sculpture" %>
        </div>

        <div class="search_category">
          <%= label_tag "Photography"%>
          <%= radio_button_tag 'category', "Photography"%>
        </div>

        <div class="search_category">
          <%= label_tag "Oil Painting"%>
          <%= radio_button_tag 'category', "Oil Painting"%>
        </div>

        <div class="search_category">
          <%= label_tag "Painting"%>
          <%= radio_button_tag 'category', "Painting"%>
        </div>

        <div class="search_category">
          <%= label_tag "Illustration"%>
          <%= radio_button_tag 'category', "Illustration"%>
        </div>
        <%= submit_tag "Search", class: "categories-btn" %>
      </div>

      <% end %>
    </div>

    <div></div>

    <% @pieces.each do |piece| %>

    <li>
      <%= link_to piece_path(piece) do %>

      <div class="card">
        <% if piece.photo.present? %>
        <%= cl_image_tag(piece.photo.key, class:"card__image", height: 800, width: 800, crop: :thumb) %>
        <% end %>

        <div class="card__overlay">
          <div class="card__header">
            <svg class="card__arc" xmlns="http://www.w3.org/2000/svg">
              <path /></svg>

            <% if piece.user.photo.present? %>
            <%= cl_image_tag(piece.user.photo.key, class:"card__thumb", height: 800, width: 800, crop: :thumb) %>
            <% else %>
            <img class="card__thumb" src="https://i.imgur.com/sjLMNDM.png" alt="" />
            <% end %>

            <div class="card__header-text">
              <h3 class="card__title"><%= piece.name %></h3>
              <span class="card__status">Price: <%= piece.price %>$ </span>
            </div>

          </div>
          <p class="card__description"><%= piece.description %></p>
          <p class="card__description"><b>Category:</b> <%= piece.category %> | <b>Height:</b> <%= piece.height %> |
            <b>Length:</b> <%= piece.length %></p>
        </div>
      </div>
      <% end %>
    </li>
    <% end %>
  </div>

  <div id="map" style="width: 600px;" data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

</div>

app/views/pieces/new.html.erb
<div class="new-page">

  <div class="row justify-content-center">

    <div class="new-form mt-3">
      <%= simple_form_for(@piece) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="form-inputs">
          <%= f.input :name, placeholder: "title of the piece" %>
          <div class="dimensions">
            <%= f.input :height, :label => "Height", placeholder: "in cm"  %>
            <%= f.input :length, :label => "Length", placeholder: "in cm" %>
          </div>
          <%= f.input :price, :label => "Price ($) per day" %>
          <%= f.input :address %>
          <%= f.input :artist, placeholder: "full name" %>
          <%= f.input :description, placeholder: "few words about the art piece" %>
          <%= f.input :photo, as: :file %>
          <div class="category d-flex justify-content-center">
            <%= f.select :category, options_for_select(['Sculpture', 'Photography', 'Oil Painting', 'Painting', 'Illustration']), prompt: "Choose your category" %>
          </div>
        </div>
        <div class="d-flex justify-content-center mb-3 mt-3">
          <div class="form-actions btn btn-ghost">
            <%= f.button :submit %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <br>

  <div class="d-flex justify-content-center mt-3">
    <%= link_to "Back", pieces_path, class: "btn btn-ghost" %>
  </div>

  <br><br>

</div>

app/views/pieces/show.html.erb
<div class="row justify-content-center mt-5">
  <div class="col-md-8">
    <div class="thumbnail">
      <% if @piece.photo.present? %>
      <%= cl_image_tag(@piece.photo.key, class:"card__image shadow p-3 mb-4 bg-white rounded") %>
      <% end %>
      <div class="d-flex justify-content-between">
        <div class="caption w-50 ">
          <h1 class="mt-2"><%= @piece.name %></h1>
          <p><%= @piece.description %></p>
          <div>
            <% if @piece.user == current_user %>
            <%= link_to "Edit", edit_piece_path(@piece), class: "btn btn-search"%>
            <% end %>
            <% if @piece.user == current_user %>
            <%= link_to "Delete", @piece, method: :delete, data: { confirm: "Are you sure you want to delete #{@piece.name}?" }, class: "btn btn-search" %>
            <% end %>
            <%= link_to "Create a booking", new_piece_booking_path(@piece), class: "btn btn-search" unless @piece.user == current_user%>
          </div>
        </div>
        <div class="details">
          <h2 class="piece_price_show"><%= @piece.price %>$ Per Day</h2>
          <p class="mb-1"><b>Height:</b> <%= @piece.height %>cm | <b>Length:</b> <%= @piece.length %>cm</p>
          <p class="m-0"><b>Category:</b> <%= @piece.category %></p>
          <p><b>By:</b> <%= @piece.artist %></p>
        </div>
      </div>
      </a>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    This footer was made with <strong>love</strong> by the FastTrack team
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo32.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <%= link_to "Rent your art", new_piece_path , class: "nav-link btn-search" %>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">


    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", "#", class: "dropdown-item" %>
            <%= link_to "Rent your art", new_piece_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
<h2><%= @user.first_name.capitalize%>'s Profile</h2>
<% @user.pieces.bookings.each do |n| %>
<%= n %>
<% end %>
</div>